# Generated by Django 4.2.1 on 2023-05-25 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.IntegerField(db_index=True, default=1),
            preserve_default=False,
        ),
    ]
