# Generated by Django 4.2.1 on 2023-05-27 04:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0008_rename_datetimecreate_purchase_date_time_create_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Purchase',
            new_name='UserPurchase',
        ),
        migrations.RenameModel(
            old_name='PurchaseLinks',
            new_name='UserPurchaseLinks',
        ),
        migrations.CreateModel(
            name='UserBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField(db_index=True, max_length=150)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
