# Generated by Django 4.2.1 on 2023-05-27 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_rename_userpurchaselinks_productlink_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpurchaselink',
            name='slug',
            field=models.SlugField(default=1, max_length=150, unique=True),
            preserve_default=False,
        ),
    ]
