# Generated by Django 4.2.1 on 2023-05-27 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_userpurchaselink_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbalance',
            name='balance',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
