# Generated by Django 4.2.1 on 2023-05-27 14:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0013_alter_userbalance_balance'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserPurchase',
            new_name='Purchase',
        ),
    ]
